name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw64/mingw-w64-x86_64-qt5-static
            mingw-w64-x86_64-openssl

      - name: Download and Install Dokan
        shell: bash
        run: |
          # Spécifiez une version spécifique de Dokan (par exemple, 1.1.0)
          curl -L -o dokan.zip https://github.com/dokan-dev/dokany/releases/download/v1.1.0/Dokan-1.1.0-x64.zip
          
          # Vérifiez si le téléchargement a réussi
          if [ $? -ne 0 ]; then
            echo "Failed to download Dokan"
            exit 1
          fi

          # Extraction
          unzip dokan.zip -d dokan
          
          # Vérifiez si l'extraction a réussi
          if [ ! -f dokan/Dokan1.dll ]; then
            echo "Dokan1.dll not found"
            exit 1
          fi
          
          # Copier le DLL dans le bon dossier
          mkdir -p /mingw64/bin
          cp dokan/Dokan1.dll /mingw64/bin/
          
          # Cleanup
          rm -rf dokan dokan.zip

      - name: Build
        shell: msys2 {0}
        run: |
          ln -s $(pwd) ~/NxNandManager
          cd ~/NxNandManager/NxNandManager/gui
          /mingw64/qt5-static/bin/qmake.exe NxNandManager.pro 'CONFIG += STATIC ARCH64'
          make -j"$(nproc)"
          mkdir -p $GITHUB_WORKSPACE/bin
          cp release/NxNandManager.exe $GITHUB_WORKSPACE/bin
          cp /mingw64/bin/Dokan1.dll $GITHUB_WORKSPACE/bin

      - uses: actions/upload-artifact@v3
        with:
          name: NxNandManager
          path: bin/*
